import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import Navbar from '../components/Navbar'
import Mainpage from './Mainpage'
import About from './About'
import Product from './Product'
import Contact from './contact'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>webpage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      
             </Head>
      <main>
          <div className=''>
         <Navbar/>
         <Mainpage/>
        <About/>
        <Product/>
        <Contact/>
       
          </div>
     
      </main>
    </>
  )
}
